#!/bin/sh
echo $(tput setaf 6) "what action:" $(tput sgr0)
read ac
if [ $ac = cd ]; then
 echo $(tput setaf 6) "to what folder:" $(tput sgr0)
 read cd
 clear
 cd $cd
 ls
else
 if [ $ac = del ]; then
  echo $(tput setaf 6) "delete what item:" $(tput sgr0)
  read del
  clear
  rm $del
  ls
 else
  clear
  $ac
  read none
  ls
 fi
fi
sbashfm
